# Made by Puyodead1
settings:
  enchanting_tables:
    enabled: false # Setting this to true will change enchanted books to crystals in enchantment tables
    require_lapis: true

  merchants:
    # Changing this from true to false will not affect any merchants that have already been interacted with!
    enabled: false # Setting this to true will change enchanted books to crystals in merchant trades
  item:
    material: NETHER_STAR # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Don't use legacy names)
    display_name: "&6Enchantment Crystal &8[&7%ENCHANTMENT_COUNT% %ENCHANTMENT_STRING%&8]"
    enchant_lore: "&7%ENCHANTMENT_NAME% %ENCHANTMENT_LEVEL%"
    lore:
      - ""
      - "&7Right click on an item to apply."

messages:
  enchantment_plural: "Enchantments"
  enchantment_singular: "Enchantment"
  already_enchanted: "&cThat item already contains this enchantment!"
  enchantment_success: "&aSuccessfully applied &e%ENCHANTMENT_NAME% %ENCHANTMENT_LEVEL% &ato &e%ITEM_DISPLAY_NAME%&a!"
  enchantment_bounds_error: "&cEnchantment level out of bounds! Must be between %ENCHANTMENT_LEVEL_START% and %ENCHANTMENT_LEVEL_MAX%"
  enchantment_conflict: "&e%OTHER_ENCHANTMENT_NAME% &cconflicts with this enchantment&c!"
  enchantment_max_exceed: "&e%ENCHANTMENT_NAME% &ccannot be combined as it would exceed the maximum level!"
  enchantment_upgraded: "&aSuccessfully upgraded &e%ENCHANTMENT_NAME% &afrom level &e%ENCHANTMENT_LEVEL_OLD% &ato level &e%ENCHANTMENT_LEVEL_NEW%&a!"
  invalid_item: "&e%ENCHANTMENT_NAME% &ccannot be applied to &e%ITEM_DISPLAY_NAME%!"
  invalid_player: "&cInvalid player specified!"
  invalid_enchantment: "&cInvalid Enchantment! Check &e/ecr enchants &cfor a list of valid enchantments."
  missing_permission: "&cYou do not have permission to run that command!"
  crystal_given: "&aAdded &ex%CRYSTAL_AMOUNT% %ENCHANTMENT_NAME% &6Enchantment Crystal &ato your inventory!"
  crystal_given_to_player: "&a%PLAYER_NAME% has been given &ex%CRYSTAL_AMOUNT% %ENCHANTMENT_NAME%&a!"
  crystal_received: "&aYou have been given &ex%CRYSTAL_AMOUNT% %ENCHANTMENT_NAME% &afrom &e%PLAYER_NAME%&a!"
  creative_error: "&cYou cannot apply crystals in creative mode!"
  add_invalid_item: "&cYou must be holding an &6Enchantment Crystal &cto apply enchants!"
  add_success: "&e%ENCHANTMENT_NAME% &ahas been added to the crystal!"
