name: EnchantCrystals
version: '${project.version}'
main: me.puyodead1.enchantcrystals.EnchantCrystals
api-version: 1.19
softdepend: [ AdvancedEnchantments, EnchantmentSolution ]
authors: [ Puyodead1 ]
commands:
  enchantcrystals:
    description: Give a crystal
    aliases: [ ecr ]
    usage: /ecr <enchants|give|add> <enchant name> [level] [amount] [player]
