name: EnchantCrystals
version: '${project.version}'
main: me.puyodead1.enchantcrystals.EnchantCrystals
api-version: 1.19
softdepend: [ AdvancedEnchantments, EnchantmentSolution ]
authors: [ Puyodead1 ]
commands:
  test:
    description: test
    usage: /test
