name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: '17.0.1+12'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Helper
        id: helper
        run: "chmod +x ./.github/release-helper && bash ./.github/release-helper"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Artifact Directory
        run: "mkdir ./artifacts"

      - name: Find and Move JARS
        run: "mv `find ./target -name EnchantCrystals-*.jar -print` ./artifacts"

      - name: Upload to release
        uses: Puyodead1/upload-to-release@master
        with:
          args: './artifacts/EnchantCrystals-*.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - id: set_json
#        run: echo "::set-output name=json::[{\"title\":\"New Release!\",\"url\":\"${{ steps.create_release.outputs.url }}\",\"description\":\"A new release has been published for ${{ github.repository }}\",\"color\":3329330,\"timestamp\":\"2021-06-15T00:22:23.172Z\",\"author\":{\"name\":\"${{ github.repository }}\"},\"fields\":[{\"name\":\"Build\",\"value\":\"${{ github.run_id }}\"},{\"name\":\"Changes\",\"value\":\"${{ steps.helper.outputs.COMMIT_MESSAGE }}\"}]}]"
#      - name: Discord Release Message
#        if: success()
#        uses: Ilshidur/action-discord@master
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#          DISCORD_EMBEDS: ${{ steps.set_json.outputs.json }}